### PR TITLE
Improve protobuf test

### PR DESCRIPTION
**Pull request by star-hengxing**
https://github.com/xmake-io/xmake/issues/5399

### CODE REVIEW

**Comment by star-hengxing** [comment]
现在 package 行为默认 `package:addenv("PATH", "bin")` ？导致 non-host plat 的 package bin 也引入了环境变量，需要改成这样才能 work。
```lua
if package:is_cross() then
    os.tryrm(package:installdir("bin/*"))
end
```

**Comment by waruqi** [comment]
> 现在 package 行为默认 `package:addenv("PATH", "bin")` ？导致 non-host plat 的 package bin 也引入了环境变量，需要改成这样才能 work。
> 
> ```lua
> if package:is_cross() then
>     os.tryrm(package:installdir("bin/*"))
> end
> ```

cross 下不设置 bin env 不就好了么。。另外，tests example 里面没必要再去 is_cross，太复杂

**Comment by star-hengxing** [comment]
> cross 下不设置 bin env 不就好了么

没设置也一样，即使是头文件库。
```lua
package("jsoncons")

    set_kind("library", {headeronly = true})
    set_homepage("https://danielaparker.github.io/jsoncons/")
    set_description("A C++, header-only library for constructing JSON and JSON-like data formats, with JSON Pointer, JSON Patch, JSONPath, JMESPath, CSV, MessagePack, CBOR, BSON, UBJSON")
    set_license("BSL-1.0")

    set_urls("https://github.com/danielaparker/jsoncons/archive/$(version).zip",
             "https://github.com/danielaparker/jsoncons.git")

    add_versions("v0.177.0", "ce9f0ee1dbcdc67733cf9e50b038f81d36121b800f8d12a3d89ea5232457edd6")
    add_versions("v0.176.0", "71a618219b62a2bbcc46efac98696574581e343cd98ef33e5e1bd8db182005d9")
    add_versions("v0.170.2", "81ac768eecb8cf2613a09a9d081294895d7afd294b841166b4e1378f0acfdd6e")
    add_versions("v0.158.0", "7ad7cc0e9c74df495dd16b818758ec2e2a5b7fef8f1852841087fd5e8bb6a6cb")

    on_install(function (package)
        os.cp("include", package:installdir())
    end)

    on_test(function (package)
        assert(package:has_cxxfuncs("jsoncons::json::parse(\"\")", {configs = {languages = "c++11"}, includes = {"jsoncons/json.hpp", "jsoncons_ext/jsonpath/jsonpath.hpp"}}))
    end)

```

```
{
    arch = "x64",
    artifacts = {
        installdir = [[C:\Users\star\AppData\Local\.xmake\packages\j\jsoncons\v0.178.0\888254b15a2943eca057a832ec39e18a]]
    },
    configs = {
        cmake = true,
        debug = true,
        pic = true,
        runtimes = "MD",
        shared = true
    },
    deps = { },
    description = "A C++, header-only library for constructing JSON and JSON-like data formats, with JSON Pointer, JSON Patch, JSONPath, JMESPath, CSV, MessagePack, CBOR, BSON, UBJSON",
    envs = {
        PATH = {
            "bin"
        }
    },
    kind = "library",
    librarydeps = { },
    license = "BSL-1.0",
    mode = "debug",
    name = "jsoncons",
    pathenvs = {
        "CMAKE_PREFIX_PATH",
        "LD_LIBRARY_PATH",
        "PATH",
        "ACLOCAL_PATH",
        "PKG_CONFIG_PATH",
        "PYTHONPATH",
        "DYLD_LIBRARY_PATH"
    },
    plat = "windows",
    repo = {
        commit = "68f47abe7f76dd295ee8f3c9188a54377bb61928",
        name = "local-repo",
        url = [[A:\project\xmake\xmake-repo]]
    },
    version = "v0.178.0"
}
```

**Comment by waruqi** [comment]
仅 win 上有这个问题，没处理 headeronly ，因为 lib 也会有 bin/dll 所以之前直接加了

https://github.com/xmake-io/xmake/blob/f2c9a6c2669c90e275753e1c1628dad7fca595da/xmake/core/package/package.lua#L1074

**Comment by waruqi** [comment]
> > cross 下不设置 bin env 不就好了么
> 
> 没设置也一样，即使是头文件库。
> 
> ```lua
> package("jsoncons")
> 
>     set_kind("library", {headeronly = true})
>     set_homepage("https://danielaparker.github.io/jsoncons/")
>     set_description("A C++, header-only library for constructing JSON and JSON-like data formats, with JSON Pointer, JSON Patch, JSONPath, JMESPath, CSV, MessagePack, CBOR, BSON, UBJSON")
>     set_license("BSL-1.0")
> 
>     set_urls("https://github.com/danielaparker/jsoncons/archive/$(version).zip",
>              "https://github.com/danielaparker/jsoncons.git")
> 
>     add_versions("v0.177.0", "ce9f0ee1dbcdc67733cf9e50b038f81d36121b800f8d12a3d89ea5232457edd6")
>     add_versions("v0.176.0", "71a618219b62a2bbcc46efac98696574581e343cd98ef33e5e1bd8db182005d9")
>     add_versions("v0.170.2", "81ac768eecb8cf2613a09a9d081294895d7afd294b841166b4e1378f0acfdd6e")
>     add_versions("v0.158.0", "7ad7cc0e9c74df495dd16b818758ec2e2a5b7fef8f1852841087fd5e8bb6a6cb")
> 
>     on_install(function (package)
>         os.cp("include", package:installdir())
>     end)
> 
>     on_test(function (package)
>         assert(package:has_cxxfuncs("jsoncons::json::parse(\"\")", {configs = {languages = "c++11"}, includes = {"jsoncons/json.hpp", "jsoncons_ext/jsonpath/jsonpath.hpp"}}))
>     end)
> ```
> 
> ```
> {
>     arch = "x64",
>     artifacts = {
>         installdir = [[C:\Users\star\AppData\Local\.xmake\packages\j\jsoncons\v0.178.0\888254b15a2943eca057a832ec39e18a]]
>     },
>     configs = {
>         cmake = true,
>         debug = true,
>         pic = true,
>         runtimes = "MD",
>         shared = true
>     },
>     deps = { },
>     description = "A C++, header-only library for constructing JSON and JSON-like data formats, with JSON Pointer, JSON Patch, JSONPath, JMESPath, CSV, MessagePack, CBOR, BSON, UBJSON",
>     envs = {
>         PATH = {
>             "bin"
>         }
>     },
>     kind = "library",
>     librarydeps = { },
>     license = "BSL-1.0",
>     mode = "debug",
>     name = "jsoncons",
>     pathenvs = {
>         "CMAKE_PREFIX_PATH",
>         "LD_LIBRARY_PATH",
>         "PATH",
>         "ACLOCAL_PATH",
>         "PKG_CONFIG_PATH",
>         "PYTHONPATH",
>         "DYLD_LIBRARY_PATH"
>     },
>     plat = "windows",
>     repo = {
>         commit = "68f47abe7f76dd295ee8f3c9188a54377bb61928",
>         name = "local-repo",
>         url = [[A:\project\xmake\xmake-repo]]
>     },
>     version = "v0.178.0"
> }
> ```

试下这个 patch ，改了 https://github.com/xmake-io/xmake/pull/5959

**Pull request merged**
