### PR TITLE
Strict compatibility for package linkdeps

### PR DESCRIPTION
**Pull request by waruqi**
https://github.com/xmake-io/xmake/issues/2719

we can use `set_policy("package.librarydeps.strict_compatibility, true)` to limit package compatibility in package().

```lua
package("libpng")
    add_deps("zlib")
    set_policy("package.librarydeps.strict_compatibility, true)
```

Or we can also use `set_policy("package.librarydeps.strict_compatibility, true)` to limit all packages compatibility in project xmake.lua

```lua
set_policy("package.librarydeps.strict_compatibility, true)
add_requires("libpng")
```

for example:

I updated zlib 1.2.11 => 1.2.12 in package()

### Dependency compatibility is not strictly tested by default

```console
$ xmake f -c
do nothing
```

### Enable strict compatibility for librarydeps

```console
$ xmake f -c --policies=package.librarydeps.strict_compatibility
note: install or modify (m) these packages (pass -y to skip confirm)?
in local-repo:
  -> libpng v1.6.37 [deps:*zlib]
please input: y (y/n/m)
```

### CODE REVIEW

**Comment by SirLynix** [comment]
This sounds great! However I don't think only linked packages should be considered, since you can have a lot of code coming from header-only libs as well.

**Comment by waruqi** [comment]
I will continue to improve it tomorrow, right now it is not fully working

**Comment by waruqi** [comment]
> This sounds great! However I don't think only linked packages should be considered, since you can have a lot of code coming from header-only libs as well.

It is only the name that is ambiguous, it actually already contains the headeronly library.

https://github.com/xmake-io/xmake/blob/ad0112c31cf46fa7e42ba79efdc60c14dafd6416/xmake/modules/private/action/require/impl/package.lua#L293

**Comment by waruqi** [comment]
I have rename linkdeps to librarydeps and it works fine for me.

you can try it. @SirLynix

**Pull request merged**
