### PR TITLE
Separate build rules for specific language files from action/build

### PR DESCRIPTION
**Pull request by waruqi**
Make action/build more lightweight, just include the processing logic for the rules. Extract c++ related build action into the c++ rules. 

This way we can more easily extend and customize the language-specific build process and prepare for implementing C++ modules #386. 

Roadmap
- [x] Rules
  - [x] `c++`
    - [x] `c.build`
      - [x] `c.build.pcheader` (build precompiled header)
    - [x] `c++.build`
      - [x] `c++.build.pcheader`
      - [ ] `c++.build.modules`  @see https://github.com/xmake-io/xmake/issues/386
  - [x] `win.sdk.resource`
  - [x] `objc++`
    - [x] `objc.build`
    - [x] `objc++.build`
  - [x] `swift`
    - [x] `swift.build`
  - [x] `rust`
    - [x] `rust.build`
  - [x] `go`
    - [x] `go.build`
  - [x] `dlang`
    - [x] `dlang.build`
  - [x] `cuda`
    - [x] `cuda.build`
      - [x] `cuda.build.devlink`
    - [x] `cuda.gencodes`
  - [x] `utils`
    - [x] `utils.merge.object`, `add_files("*.o", "*.obj")`
    - [x] `utils.merge.archive`, `add_files("*.a", "*.lib")`
 - [x] Modules
   - [x] private.tools.ccache
   - [x] private.action.build.object
   - [x] private.action.build.pcheader

### CODE REVIEW

**Comment by waruqi** [comment]
@OpportunityLiu  我这边重构了下build action，打薄后，逐步吧build实现分离到特定的rules中，改动比较大，你这边试试是否运行正常，比如cuda/vsxmake深得，如果没啥问题，我就先merge进去了

我这边初步测试各个模块，没测出啥问题。

**Comment by OpportunityLiu** [comment]
图片

**Comment by waruqi** [comment]
我修复了

**Comment by waruqi** [comment]
c++.build.modules @see https://github.com/xmake-io/xmake/pull/569

**Pull request merged**
