### PR TITLE
Add module redeclaration check

### LINKED ISSUE #4770: C++模块接口重复定义时会静默成功
### Xmake 版本

v2.8.7+HEAD.da279272a

### 操作系统版本和架构

Windows 10 专业版 2004

### 描述问题

当存在多个同名的 C++ 模块接口单元时，xmake 会编译成功，没有报错。

### 期待的结果

作为对比，CMake 会产生链接错误：
```
B.obj : error LNK2005: "int __cdecl f(void)" (?f@@YAHXZ::<!A>) 已经在 A.obj 中定义
ModuleTest.exe: fatal error LNK1169: 找到一个或多个多重定义的符号
```

个人认为 xmake 应该可以在依赖扫描阶段就发现模块重复定义，并报错。

### 工程配置

**xmake.lua**
```lua
set_languages("c++20")
target("ModuleTest")
    set_kind("binary")
    add_files("src/*.cpp", "src/*.mpp")
```

**Main.cpp**
```cpp
#include <iostream>
import A;
int main() {
    std::cout << f() << std::endl;
}
```

**A.mpp**
```cpp
export module A;
export int f() { return 1; }
```

**B.mpp** （与 **A.mpp** 内容相同）
```cpp
export module A;
export int f() { return 1; }
```

### 附加信息和错误日志

除此之外还希望能够提前检测出模块分区重复定义，例如：

**A.mpp**
```cpp
export module A;
export import :B;
```

**B.mpp**
```cpp
export module A:B;
export int f();
```

**B.cpp**
```cpp
module A:B;
int f() { return 1; }
```

实际报错：
```
error: A.mpp
A.mpp(3): error C7620: 无法导出模块分区 "B"，它不是接口单元
```
可能会导致一些迷惑，所以希望这种情况也能在依赖扫描阶段识别出。

---

另附相关的 C++ 标准节选：

**[C++20 [module.unit]p2](https://timsong-cpp.github.io/cppwp/n4868/module.unit#2)**
> A named module shall contain exactly one module interface unit with no module-partition, known as the primary module interface unit of the module; no diagnostic is required.

**[C++20 [module.unit]p3](https://timsong-cpp.github.io/cppwp/n4868/module.unit#3)**
> A named module shall not contain multiple module partitions with the same module-partition.

虽然是 no diagnostic required，不过能有更友好的报错信息总是好的。

### PR DESCRIPTION
**Pull request by SuperSodaSea**
Add function `modules_support.dependency_scanner.check_module_redeclaration` to detect module interface / partition redeclaration before build.

Fixes #4770.

### CODE REVIEW

**Comment by SuperSodaSea** [comment]
刚发现有个测试用来确保模块重复声明时的链接顺序（[tests/projects/c++/modules/link_order](https://github.com/xmake-io/xmake/blob/76af94c04ba55dfe7a5087ce76dfeba4a709ba46/tests/projects/c%2B%2B/modules/link_order/xmake.lua)）。也许应该加一个 flag 来开启重复定义的检查？不过我好像想不出有什么场景下模块重复声明是有用的。

**Comment by waruqi** [comment]
我觉得这个不应该在 xmake 层面去检测，而是得让 linker 自己去检测和报错。。

既然你 issues 里面提到 cmake 能报错，说明它可能把两个都同时 link 了，被 linker 检测出来了，而 xmake 里面可能仅仅是由于少传了一个 obj 给 linker ，导致没法被检测到，那可以改进下实现，让 xmake 把所有依赖的 obj 都传给 linker 才对。

>  B.obj : error LNK2005: "int __cdecl f(void)" (?f@@YAHXZ::<!A>) 已经在 A.obj 中定义
ModuleTest.exe: fatal error LNK1169: 找到一个或多个多重定义的符号 

首先，xmake 内置的 dependency_scanner 实现，仅仅是 编译器没有原生支持时候的 fallback 方案，如果编译器支持，也是用编译器的实现。 毕竟 xmake 提供的扫描实现方案，并不是完全可靠的。

另外，在 xmake 层面去检测这些，也会影响编译效率，尤其是工程变得庞大，模块依赖层次结构复杂的时候，这种检测是非常耗时的。

**Comment by waruqi** [comment]
@Arthapz any idea?

**Comment by Arthapz** [comment]
> @Arthapz any idea?

Oh sorry didn't saw the PR i'lol Check very soon

**Comment by Arthapz** [comment]
so after some tests, you can enable the CMake behavior by deleting this line https://github.com/xmake-io/xmake/blob/a6b4dd23700f2fe50c51327d16dc3c385bbb9c84/xmake/rules/c%2B%2B/modules/modules_support/dependency_scanner.lua#L186 which cull duplicate modules

and changing this one https://github.com/xmake-io/xmake/blob/a6b4dd23700f2fe50c51327d16dc3c385bbb9c84/xmake/rules/c%2B%2B/modules/modules_support/builder.lua#L275 to ` local job_name = cppfile` 
to actually build the duplicated module so the objectfile is passed to the linker
```
xmake -v
checking for platform ... linux
checking for architecture ... x86_64
checking for gcc ... /usr/bin/gcc
checking for zig ... ⭕
checking for zig ... ⭕
checking for gcc ... /usr/bin/gcc
checking for the c++ compiler (cxx) ... gcc
checking for /usr/bin/gcc ... ✔
checking for flags (-fPIC) ... ✔
checking for flags (gcc_modules_ts) ... ✔
checking for flags (gcc_deps_format) ... ⭕
checking for flags (gcc_deps_file) ... ⭕
checking for flags (gcc_deps_output) ... ⭕
[  0%]: <ModuleTest> generating.module.deps src/main.cpp
checking for flags (-std=c++20) ... ✔
checking for flags (-D_GLIBCXX_USE_CXX11_ABI=0) ... ✔
/usr/bin/gcc -E -x c++ -m64 -std=c++20 -D_GLIBCXX_USE_CXX11_ABI=0 src/main.cpp -o build/.gens/ModuleTest/linux/x86_64/release/rules/bmi/cache/modules/10b08683/main.cpp.i
[  0%]: <ModuleTest> generating.module.deps src/B.mpp
/usr/bin/gcc -E -x c++ -m64 -std=c++20 -D_GLIBCXX_USE_CXX11_ABI=0 src/B.mpp -o build/.gens/ModuleTest/linux/x86_64/release/rules/bmi/cache/modules/10b08683/B.mpp.i
[  0%]: <ModuleTest> generating.module.deps src/A.mpp
/usr/bin/gcc -E -x c++ -m64 -std=c++20 -D_GLIBCXX_USE_CXX11_ABI=0 src/A.mpp -o build/.gens/ModuleTest/linux/x86_64/release/rules/bmi/cache/modules/10b08683/A.mpp.i
checking for flags (gcc_module_mapper) ... ✔
[ 25%]: <ModuleTest> compiling.module.release A
/usr/bin/gcc -c -m64 -std=c++20 -fmodules-ts -D_GLIBCXX_USE_CXX11_ABI=0 -fmodule-mapper=/tmp/.xmake1000/240227/ModuleTest/src/A.mpp -x c++ -o build/.objs/ModuleTest/linux/x86_64/release/src/A.mpp.o sr
c/A.mpp
[ 25%]: <ModuleTest> compiling.module.release A
/usr/bin/gcc -c -m64 -std=c++20 -fmodules-ts -D_GLIBCXX_USE_CXX11_ABI=0 -fmodule-mapper=/tmp/.xmake1000/240227/ModuleTest/src/B.mpp -x c++ -o build/.objs/ModuleTest/linux/x86_64/release/src/B.mpp.o sr
c/B.mpp
checking for flags (-fdiagnostics-color=always) ... ✔
[ 62%]: compiling.release src/main.cpp
/usr/bin/gcc -c -m64 -std=c++20 -fmodules-ts -D_GLIBCXX_USE_CXX11_ABI=0 -fmodule-mapper=/tmp/.xmake1000/240227/ModuleTest/src/main.cpp -o build/.objs/ModuleTest/linux/x86_64/release/src/main.cpp.o src
/main.cpp
checking for flags (-MMD -MF) ... ✔
checking for g++ ... /usr/bin/g++
checking for the linker (ld) ... g++
checking for /usr/bin/g++ ... ✔
checking for flags (-fPIC) ... ✔
[ 75%]: linking.release ModuleTest
/usr/bin/g++ -o build/linux/x86_64/release/ModuleTest build/.objs/ModuleTest/linux/x86_64/release/src/main.cpp.o build/.objs/ModuleTest/linux/x86_64/release/src/A.mpp.o build/.objs/ModuleTest/linux/x8
6_64/release/src/B.mpp.o -m64
/usr/bin/ld : build/.objs/ModuleTest/linux/x86_64/release/src/B.mpp.o : dans la fonction « f@A() » :
B.mpp:(.text+0x0) : définitions multiples de « f@A() »; build/.objs/ModuleTest/linux/x86_64/release/src/A.mpp.o:A.mpp:(.text+0x0) : défini pour la première fois ici
/usr/bin/ld : build/.objs/ModuleTest/linux/x86_64/release/src/B.mpp.o : dans la fonction « initializer for module A » :
B.mpp:(.text+0xb) : définitions multiples de « initializer for module A »; build/.objs/ModuleTest/linux/x86_64/release/src/A.mpp.o:A.mpp:(.text+0xb) : défini pour la première fois ici
collect2: erreur: ld a retourné le statut de sortie 1
❗ error: execv(/usr/bin/g++ -o build/linux/x86_64/release/ModuleTest build/.objs/ModuleTest/linux/x86_64/release/src/main.cpp.o build/.objs/ModuleTest/linux/x86_64/release/src/A.mpp.o build/.objs/Mod
uleTest/linux/x86_64/release/src/B.mpp.o -m64) failed(1)
```

**Comment by SuperSodaSea** [comment]
@Arthapz Looks cool, do you think this could be the default behavior for xmake?

**Comment by Arthapz** [comment]
> @Arthapz Looks cool, do you think this could be the default behavior for xmake?

sure, if @waruqi is okay with this, you can update ur PR with the modification hinted

**Comment by waruqi** [comment]
> > @Arthapz Looks cool, do you think this could be the default behavior for xmake?
> 
> sure, if @waruqi is okay with this, you can update ur PR with the modification hinted
> 
> EDIT: it may require some work on the should_build / mark_build functions

I'm ok.

**Comment by SuperSodaSea** [comment]
Okay, I'll create a new PR for this.

**Pull request closed without merging**
