### PR TITLE
Fix VS toolset v144

### PR DESCRIPTION
**Pull request by SirLynix**
Visual Studio toolset v144 doesn't exist, updating to Visual Studio 17.10 will make XMake fail to generate vs projects with the following error:
```
The builds tools for v144 (Platform Toolset = 'v144') cannot be found. To build using the v144 build tools, either click the Project menu or right-click the solution, and then select "Update VC++ Projects...". Install v144 to build using the v144 build tools.
```

There are no v144 tools, but VS stills reports it in detect.sdks.find_vstudio:
```
          VCToolsVersion = "14.40.33807",
``` 

<details>
  <summary>detect.sdks.find_vstudio</summary>
  
  ```lua
  {
    "2022" = {
      version = "17.0",
      vcvarsall_bat = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat",
      vcvarsall = {
        arm64 = {
          VS170COMNTOOLS = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\",
          LIBPATH = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319",
          UniversalCRTSdkDir = "C:\Program Files (x86)\Windows Kits\10\",
          VCInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\",
          DevEnvdir = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\",
          LIB = "C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\arm64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\arm64",
          VCToolsVersion = "14.40.33807",
          ExtensionSdkDir = "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs",
          VSCMD_ARG_app_plat = "Desktop",
          PATH = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\DiagnosticsHub\Collector;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\VulkanSDK\1.3.261.1\Bin;C:\Program Files (x86)\SCE\Common\SceVSI-VS17\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\xmake;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\CMake\bin;C:\Program Files\GitHub CLI\;C:\Users\lynix\AppData\Local\Programs\Python\Launcher\;C:\Users\lynix\.cargo\bin;C:\Users\lynix\AppData\Local\Microsoft\WindowsApps;C:\Users\lynix\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\lynix\AppData\Local\GitHubDesktop\bin;C:\Users\lynix\.dotnet\tools;C:\Program Files\OpenCppCoverage;C:\Users\lynix\AppData\Roaming\npm;c:\users\lynix\appdata\local\microsoft\visualstudio\17.0_8427cfbf\extensions\kixyskqi.kly;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg",
          VSCMD_ARG_TGT_ARCH = "arm64",
          VSCMD_VER = "17.10.1",
          UCRTVersion = "10.0.22621.0",
          VCIDEInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\",
          WindowsSdkDir = "C:\Program Files (x86)\Windows Kits\10\",
          VisualStudioVersion = "17.0",
          VSCMD_ARG_HOST_ARCH = "x64",
          VSInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\",
          VCToolsRedistDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Redist\MSVC\14.40.33807\",
          WindowsSDKVersion = "10.0.22621.0",
          WindowsSdkVerBinPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\",
          VCToolsInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\",
          WindowsLibPath = "C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0",
          WindowsSdkBinPath = "C:\Program Files (x86)\Windows Kits\10\bin\",
          INCLUDE = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um"
        },
        x64 = {
          VS170COMNTOOLS = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\",
          LIBPATH = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319",
          UniversalCRTSdkDir = "C:\Program Files (x86)\Windows Kits\10\",
          VCInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\",
          DevEnvdir = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\",
          LIB = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64",
          VCToolsVersion = "14.40.33807",
          ExtensionSdkDir = "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs",
          VSCMD_ARG_app_plat = "Desktop",
          PATH = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\DiagnosticsHub\Collector;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\VulkanSDK\1.3.261.1\Bin;C:\Program Files (x86)\SCE\Common\SceVSI-VS17\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\xmake;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\CMake\bin;C:\Program Files\GitHub CLI\;C:\Users\lynix\AppData\Local\Programs\Python\Launcher\;C:\Users\lynix\.cargo\bin;C:\Users\lynix\AppData\Local\Microsoft\WindowsApps;C:\Users\lynix\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\lynix\AppData\Local\GitHubDesktop\bin;C:\Users\lynix\.dotnet\tools;C:\Program Files\OpenCppCoverage;C:\Users\lynix\AppData\Roaming\npm;c:\users\lynix\appdata\local\microsoft\visualstudio\17.0_8427cfbf\extensions\kixyskqi.kly;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg",
          VSCMD_ARG_TGT_ARCH = "x64",
          VSCMD_VER = "17.10.1",
          UCRTVersion = "10.0.22621.0",
          VCIDEInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\",
          WindowsSdkDir = "C:\Program Files (x86)\Windows Kits\10\",
          VisualStudioVersion = "17.0",
          VSCMD_ARG_HOST_ARCH = "x64",
          VSInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\",
          VCToolsRedistDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Redist\MSVC\14.40.33807\",
          WindowsSDKVersion = "10.0.22621.0",
          WindowsSdkVerBinPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\",
          VCToolsInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\",
          WindowsLibPath = "C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0",
          WindowsSdkBinPath = "C:\Program Files (x86)\Windows Kits\10\bin\",
          INCLUDE = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um"
        },
        x86 = {
          VS170COMNTOOLS = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\",
          LIBPATH = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\lib\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\lib\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319",
          UniversalCRTSdkDir = "C:\Program Files (x86)\Windows Kits\10\",
          VCInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\",
          DevEnvdir = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\",
          LIB = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\lib\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\lib\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x86",
          VCToolsVersion = "14.40.33807",
          ExtensionSdkDir = "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs",
          VSCMD_ARG_app_plat = "Desktop",
          PATH = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\DiagnosticsHub\Collector;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\VulkanSDK\1.3.261.1\Bin;C:\Program Files (x86)\SCE\Common\SceVSI-VS17\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\xmake;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\CMake\bin;C:\Program Files\GitHub CLI\;C:\Users\lynix\AppData\Local\Programs\Python\Launcher\;C:\Users\lynix\.cargo\bin;C:\Users\lynix\AppData\Local\Microsoft\WindowsApps;C:\Users\lynix\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\lynix\AppData\Local\GitHubDesktop\bin;C:\Users\lynix\.dotnet\tools;C:\Program Files\OpenCppCoverage;C:\Users\lynix\AppData\Roaming\npm;c:\users\lynix\appdata\local\microsoft\visualstudio\17.0_8427cfbf\extensions\kixyskqi.kly;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg",
          VSCMD_ARG_TGT_ARCH = "x86",
          VSCMD_VER = "17.10.1",
          UCRTVersion = "10.0.22621.0",
          VCIDEInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\",
          WindowsSdkDir = "C:\Program Files (x86)\Windows Kits\10\",
          VisualStudioVersion = "17.0",
          VSCMD_ARG_HOST_ARCH = "x64",
          VSInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\",
          VCToolsRedistDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Redist\MSVC\14.40.33807\",
          WindowsSDKVersion = "10.0.22621.0",
          WindowsSdkVerBinPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\",
          VCToolsInstallDir = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\",
          WindowsLibPath = "C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0",
          WindowsSdkBinPath = "C:\Program Files (x86)\Windows Kits\10\bin\",
          INCLUDE = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um"
        }
      }
    }
  }
  ```
</details>

I have no idea what happened on Microsoft side, or maybe Visual Studio toolset shouldn't be extracted from `VCToolsVersion`.

Anyway, here's a fix where we force v143 if v144 is detected, I used a map in case more values are expected in the future.

### CODE REVIEW

**Comment by zchrissirhcz** [comment]
There is no `v144` right now.

They will reserving all of 14.4x for Visual Studio 17 2022 toolset v143:

> We will make separate announcements about MSVC compiler toolset versions beyond 14.4x (i.e., versions >= 14.50) at an appropriate time in the future.

ref:
- https://devblogs.microsoft.com/cppblog/msvc-toolset-minor-version-number-14-40-in-vs-2022-v17-10/
- https://gitlab.kitware.com/cmake/cmake/-/issues/26015
- https://github.com/opencv/opencv/pull/25638

**Comment by SirLynix** [comment]
Yes this is why the current way of detecting vs_toolset doesn't work here, but I don't have a better idea than temporary map v144 to v143

**Comment by SirLynix** [comment]
I wonder if we can use "version" (17.0) to map it to vc_toolset, like in https://cmake.org/cmake/help/latest/variable/MSVC_TOOLSET_VERSION.html#variable:MSVC_TOOLSET_VERSION

**Comment by waruqi** [comment]
> I wonder if we can use "version" (17.0) to map it to vc_toolset, like in https://cmake.org/cmake/help/latest/variable/MSVC_TOOLSET_VERSION.html#variable:MSVC_TOOLSET_VERSION


we can use "vs" version. (2022)

```lua
if vs == 2022 then
    -- map v144 to v143
end

**Comment by qudix** [comment]
https://gitlab.kitware.com/cmake/cmake/-/commit/d256581bb08799741f9a5221396a5b38b44b3f54

**Comment by SirLynix** [comment]
CMake fix is a bit like what I did, do you want me to add a check for VS version?

**Pull request merged**
