### PR TITLE
Improve C++20 modules support 

### PR DESCRIPTION
**Pull request by waruqi**
- [x] improve parallel compilation 
- [x] support headerunits (stl & user)
- [x] improve scan moduledeps 
  - [x] msvc (/scanDependencies + fallback)
  - [x] clang (fallback)
  - [x] gcc (-fdep-format=trtbd + fallback)
- [x] project generator
  - [x] support cmakelists
    - [x] gcc
    - [x] clang
    - [ ] msvc  
  - [ ] support vs (we need support add flags for sourcefiles)
  - [x] support compile_commands   
  - [x] improve and reduce cmakelists

related pr
- https://github.com/xmake-io/xmake/pull/2623
- https://github.com/xmake-io/xmake/pull/2664
- https://github.com/xmake-io/xmake/pull/2673

related issues
- https://github.com/xmake-io/xmake/issues/2114
- https://github.com/xmake-io/xmake/issues/1953
- https://github.com/xmake-io/xmake/issues/1862
- https://github.com/xmake-io/xmake/issues/1167
- https://github.com/xmake-io/xmake/issues/2410
- https://github.com/xmake-io/xmake/issues/1862
- https://github.com/microsoft/vscode-cpptools/issues/6302#issuecomment-1215554637

### CODE REVIEW

**Comment by waruqi** [comment]
@Arthapz I have improved some codes. e.g. toolchain includedirs, fix bmi flags for msvc, format code and optimize performance...

I still need to understand the code in depth, maybe it will take some time.

**Comment by Arthapz** [comment]
i'm contagiously testing it as i migrated one of my projet to C++20 modules

**Comment by Arthapz** [comment]
`
[ 12%]: ccache compiling.release gpu\src\pipeline\AccelerationStructure.cpp
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\cl.exe" -c /EHsc -nologo -W4 -WX -fp:fast -Ox -fp:fast -arch:AVX -arch:AVX2 -std:c++latest -MD -Igpu\include -Ibuild\include -Iwsi\include -Ilog\include -Iimage\include -Icore\include -D_CRT_SECURE_NO_WARNINGS -DSTORMKIT_BUILD -DSTORMKIT_WSI_ENABLED -DNOMINMAX -DWIN32_LEAN_AND_MEAN -DSTORMKIT_STATIC -external:W0 -external:IC:\Users\arthu\AppData\Local\.xmake\packages\v\volk\1.3.204\942754798b1c4d1f8ddbc4274c4ef952\include -external:W0 -external:IC:\Users\arthu\AppData\Local\.xmake\packages\v\vulkan-memory-allocator\v3.0.0\094caf233d04414380dac6196bbb6bf9\include -external:W0 -external:IC:\Users\arthu\AppData\Local\.xmake\packages\v\vulkan-headers\1.3.211+0\95ac6e2771c748cf960e06be9c230e56\include -external:W0 -external:IC:\Users\arthu\AppData\Local\.xmake\packages\g\glm\0.9.9+8\91454f3ee0be416cb9c7452970a2300f\include -external:W0 -external:IC:\Users\arthu\AppData\Local\.xmake\packages\r\robin-hood-hashing\3.12\8f234f60d20c45c085c48754fab18fbd\include -external:W0 -external:IC:\Users\arthu\AppData\Local\.xmake\packages\f\frozen\1.1.1\68615ccb2542442591d29c9ee8524902\include -external:W0 -external:IC:\Users\arthu\AppData\Local\.xmake\packages\b\backward-cpp\v1.6\40c73317488540f1b0b06e36f1a8f88f\include -external:W0 -external:IC:\Users\arthu\AppData\Local\.xmake\packages\f\fmt\9.0.0\508c3a94a0474ec387eb6df29d332910\include /bigobj /permissive- /Zc:__cplusplus /Zc:externConstexpr /Zc:inline /Zc:lambda /Zc:preprocessor /Zc:referenceBinding /Zc:strictStrings /Zc:throwingNew /wd4251 /wd4297 /wd5063 /wd4611 -DNDEBUG -Fobuild\.objs\stormkit-gpu\windows\x64\release\gpu\src\pipeline\AccelerationStructure.cpp.obj gpu\src\pipeline\AccelerationStructure.cpp
error: @programdir\modules\private\async\runjobs.lua:256: @programdir\modules\private\action\build\object.lua:90: @programdir\modules\core\tools\cl.lua:620: @programdir\core\base\os.lua:562: field '_touch' is not callable (a nil value)
stack traceback:
    [@programdir\core\base\os.lua:562]: in function 'touch'
    [@programdir\core\sandbox\modules\os.lua:206]: in function 'touch'
    [@programdir\modules\private\cache\build_cache.lua:237]: in function 'build'
    [@programdir\modules\core\tools\cl.lua:523]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:882: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>
`

i don't know if it's only on cxxmodules branch or not (i can"t test right now)

**Comment by Arthapz** [comment]
https://github.com/Arthapz/xmake/commits/cxxmodules i'm pushing on this branch now

**Comment by waruqi** [comment]
> https://github.com/Arthapz/xmake/commits/cxxmodules i'm pushing on this branch now

you can open a pr to cxxmodules branch

**Comment by waruqi** [comment]
This patch has some problems with the use of batchcmds at the moment.

1. About parallel compilation

All batchcmds:vrunv tasks added to before_buildcmd_files are executed serially, which prevents the modules from being compiled in parallel as much as possible.

Although serial compilation will always ensure that modules are compiled correctly, we need to increase the speed of compilation of modules as much as possible.

In the previous implementation, with `module_parser.build_batchjobs` in before_build_files, was able to compile in parallel as much as possible while keeping the dependencies intact.

However, the implementation of before_buildcmd_files is now necessary to provide the possibility of intelligense/compile_commands support later.

However, we can continue to add `before_build_files` to optimise parallel compilation.

- xmake build ->  before_build_files -> modules parallel compilation
- xmake project -k compile_commands/cmake/vs -> before_buildcmd_files -> serial compilation of modules

2.  batchcmds:set_depmtime and batchcmds:set_depcache can only be set once, it cannot be set more than once in a loop, as a batchcmds is a complete set of independent serial tasks.

They can only be executed or ignored at the same time

**Comment by Arthapz** [comment]
> However, we can continue to add before_build_files to optimise parallel compilation.
>
>    xmake build -> before_build_files -> modules parallel compilation
>    xmake project -k compile_commands/cmake/vs -> before_buildcmd_files -> serial compilation of modules

and how we do the switch between before_build_files and before_buildcmd_files ?

**Comment by waruqi** [comment]
We don't need to switch it, if before_build_files doesn't exist then xmake build and project generator will always use `before_buildcmd_files`.

If we also define before_build_files, then `xmake build` will use `before_build_files` in preference to `before_build_files`.

so, we can optimise build modules for `xmake build` by providing `before_build_files`, for example to provide better parallel compilation.



Translated with www.DeepL.com/Translator (free version)

**Comment by waruqi** [comment]
Of course, we can optimize the implementation of `before_build_files` later, but for now we'll give priority to improving the implementation of `before_buildcmds_files`.

**Comment by Arthapz** [comment]
I implemented a module mapper file for MSVC, it simplifies the code a little and i think i can do the same for clang

**Comment by waruqi** [comment]
mapper file does not work for clang. @Arthapz 

> $ rm -rf .xmake/; rm -rf build/; xmake f --toolchain=
llvm -c;xmake -j1
checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for SDK version of Xcode for macosx (x86_64) ... 11.3
[ 20%]: generating.cxx.module.deps src/main.cpp
[ 20%]: generating.cxx.module.deps src/foo.mpp
[ 20%]: generating.cxx.module.deps src/bar.mpp
[ 20%]: generating.cxx.module.deps src/cat.mpp
[ 20%]: generating.cxx.module.deps src/zoo.mpp
[ 20%]: generating.cxx.module.bmi zoo
[ 20%]: generating.cxx.module.bmi cat
[ 20%]: generating.cxx.module.bmi bar
error: src/bar.mpp:2:8: fatal error: module 'zoo' not found
import zoo;
~~~~~~~^~~
1 error generated.


> error: src/hello_impl.cpp:4:1: error: definition of module 'hello' is not av
ailable; use -fmodule-file= to specify path to precompiled module interface
module hello;
^
src/hello_impl.cpp:5:8: fatal error: module 'mod' not found
import mod;
~~~~~~~^~~
2 errors generated

**Comment by waruqi** [comment]
submodules example is broken for clang too

```
src/math.mpp:3:15: fatal error: module 'math.math1' not found
export import math.math1;
       ~~~~~~~^~~~
1 error generated.
```

**Comment by waruqi** [comment]
```
$ xmake clean -a; xmake f --toolchain=clang -c; xmake -rv -j1          
checking for platform ... linux
checking for architecture ... x86_64
[  0%]: generating.cxx.module.deps src/hello_impl.cpp
[  0%]: generating.cxx.module.deps src/main.cpp
[  0%]: generating.cxx.module.deps src/mod_impl.cpp
[  0%]: generating.cxx.module.deps src/hello.mpp
[  0%]: generating.cxx.module.deps src/mod.mpp
checking for flags (clang_modules_cache_path) ... ok
checking for flags (clang_emit_module_interface) ... ok
checking for flags (clang_module_file) ... ok
[ 41%]: generating.cxx.module.bmi mod
checking for flags (-std=c++20) ... ok
checking for flags (-fmodules) ... ok
/usr/bin/clang -Qunused-arguments -m64 -std=c++20 -fmodules -fbuiltin-module-map -fimplicit-modules -fno-implicit-module-maps -fmodule-file=mod=build/.gens/dependence/linux/x86_64/release/rules/modules/cache/mod.pcm -fmodule-file=hello=build/.gens/dependence/linux/x86_64/release/rules/modules/cache/hello.pcm -fmodules-cache-path=build/.gens/dependence/linux/x86_64/release/rules/modules/cache -emit-module-interface -c -x c++-module --precompile src/mod.mpp -o build/.gens/dependence/linux/x86_64/release/rules/modules/cache/mod.pcm
/usr/bin/clang -Qunused-arguments -m64 -std=c++20 -fmodules -fbuiltin-module-map -fimplicit-modules -fno-implicit-module-maps -fmodule-file=mod=build/.gens/dependence/linux/x86_64/release/rules/modules/cache/mod.pcm -fmodule-file=hello=build/.gens/dependence/linux/x86_64/release/rules/modules/cache/hello.pcm -fmodules-cache-path=build/.gens/dependence/linux/x86_64/release/rules/modules/cache build/.gens/dependence/linux/x86_64/release/rules/modules/cache/mod.pcm -c -o build/.objs/dependence/linux/x86_64/release/src/mod.mpp.o
[ 50%]: generating.cxx.module.bmi hello
/usr/bin/clang -Qunused-arguments -m64 -std=c++20 -fmodules -fbuiltin-module-map -fimplicit-modules -fno-implicit-module-maps -fmodule-file=mod=build/.gens/dependence/linux/x86_64/release/rules/modules/cache/mod.pcm -fmodule-file=hello=build/.gens/dependence/linux/x86_64/release/rules/modules/cache/hello.pcm -fmodules-cache-path=build/.gens/dependence/linux/x86_64/release/rules/modules/cache -emit-module-interface -c -x c++-module --precompile src/hello.mpp -o build/.gens/dependence/linux/x86_64/release/rules/modules/cache/hello.pcm
/usr/bin/clang -Qunused-arguments -m64 -std=c++20 -fmodules -fbuiltin-module-map -fimplicit-modules -fno-implicit-module-maps -fmodule-file=mod=build/.gens/dependence/linux/x86_64/release/rules/modules/cache/mod.pcm -fmodule-file=hello=build/.gens/dependence/linux/x86_64/release/rules/modules/cache/hello.pcm -fmodules-cache-path=build/.gens/dependence/linux/x86_64/release/rules/modules/cache build/.gens/dependence/linux/x86_64/release/rules/modules/cache/hello.pcm -c -o build/.objs/dependence/linux/x86_64/release/src/hello.mpp.o
[ 58%]: ccache compiling.release src/hello_impl.cpp
/usr/bin/clang -c -Qunused-arguments -m64 -std=c++20 -fmodules -fbuiltin-module-map -fimplicit-modules -fno-implicit-module-maps -fmodule-file=mod=build/.gens/dependence/linux/x86_64/release/rules/modules/cache/mod.pcm -fmodule-file=hello=build/.gens/dependence/linux/x86_64/release/rules/modules/cache/hello.pcm -o build/.objs/dependence/linux/x86_64/release/src/hello_impl.cpp.o src/hello_impl.cpp
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
error: src/hello_impl.cpp:4:1: error: definition of module 'hello' is not available; use -fmodule-file= to specify path to precompiled module interface
module hello;
^
src/hello_impl.cpp:16:5: error: use of undeclared identifier 'say'
    say::say(int data) : data_{data} {
    ^
src/hello_impl.cpp:19:10: error: use of undeclared identifier 'say'
    void say::hello() {
         ^
3 errors generated.
```

`src/hello_impl.cpp` is implementation of hello module, if I change `-fmodule-file=hello=xxx/hello.pcm` to `-fmodule-file=xxx/hello.pcm`, it will work for clang.

**Comment by ChuanqiXu9** [comment]
Excellent! BTW, https://github.com/alibaba/async_simple/tree/CXX20Modules is used C++20 Modules completely and it is OK to be compiled by clang15 now. I guess it might be a good test case for you.

**Comment by waruqi** [comment]
> Excellent! BTW, https://github.com/alibaba/async_simple/tree/CXX20Modules is used C++20 Modules completely and it is OK to be compiled by clang15 now. I guess it might be a good test case for you.

Thanks, there are still some improvements to be made now, and you can test this patch when it is merged.

**Comment by Arthapz** [comment]
mmmmh, when building a shared lib with header units, we may have link error because the library consummer don't have access to the header units .obj, i think i need some more reading about header units to handle that we may handle them wrong

**Comment by waruqi** [comment]
> mmmmh, when building a shared lib with header units, we may have link error because the library consummer don't have access to the header units .obj, i think i need some more reading about header units to handle that we may handle them wrong

well, you can add a shared test example in tests directory first.

**Comment by waruqi** [comment]
cmake generator work fine for gcc/clang now.

```console
$ xmake project -k cmake; cd build/; cmake ..; make 
[  0%]: generating.cxx.module.deps src/hello_impl.cpp
[  0%]: generating.cxx.module.deps src/main.cpp
[  0%]: generating.cxx.module.deps src/mod_impl.cpp
[  0%]: generating.cxx.module.deps src/hello.mpp
[  0%]: generating.cxx.module.deps src/mod.mpp
create ok!
-- The CXX compiler identification is GNU 11.3.0
-- The C compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/xmake/tests/projects/c++/modules/dependence/build
[ 20%] Generating output_dependence_ADE56AE0
[ 0%]: generating.cxx.module.bmi mod
[ 0%]: generating.cxx.module.bmi hello
[ 20%] Built target target_dependence_ADE56AE0
[ 40%] Building CXX object CMakeFiles/dependence.dir/src/hello_impl.cpp.o
[ 60%] Building CXX object CMakeFiles/dependence.dir/src/main.cpp.o
[ 80%] Building CXX object CMakeFiles/dependence.dir/src/mod_impl.cpp.o
[100%] Linking CXX executable linux/x86_64/release/dependence
[100%] Built target dependence
```

**Comment by waruqi** [comment]
The vs generator is not currently supported because it requires all cxxflags to be fetched in advance of the config phase, but some of the module's cxxflags are dynamically added in before_build_files, so they cannot be fetched.

This patch is a bit large and works mostly fine for now, so I've merged it for now, other improvements to vs generator and shared libs can be improved in a new patch separately.

**Pull request merged**
